on: [push]

jobs:
  test:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Zig
        uses: actions/setup-zig@v2
        with:
          version: 0.16.0

      - name: Setup Packages
        run: |
          apt update
          apt install -y pkg-config libwayland-dev wayland-protocols libxkbcommon-dev

      - name: Build & Test
        run: |
          zig fmt --check .
          zig build test --summary all
          zig build install --summary all

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: out-debug-${{ env.RUNNER_ARCH }}
          path: |
            zig-out/*
